dist: trusty
sudo: false

language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go install golang.org/x/tools/cmd/goyacc
  - go get github.com/golang/glog

script:
  - travis_retry $HOME/gopath/bin/goveralls -service=travis-ci